### ISSUE TITLE
Internal error upon issuing command

### ISSUE THREAD

**Issue by RoyalStarfox** [droans/klipper_extras#14]
Hello, I generally try to avoid creating an issue report until I've exhausted all other avenues, but there aren't many for this plugin quite yet!

I've added an extended macro to my config to check the time of the day and, if it is a reasonable time of day, the printer will play a jingle for me to notify that a print is done. If it's an unholy hour of the night, the printer just shut itself down, instead. The problem is, the moment I issue the macro command, the terminal just shows that there was an internal error and will not give me any further context.

Here is the section for the macro:

```
[extended_macro FINISHED]
gcode:
	(% set hour = datetime.datetime.now().hour %}
	{% if hour < 23 and hour > 7 %}
		{ ['PR9000', 'XP9001', 'SMI3', 'SMB1'] | random }
	{% else %}
		M112
	{% endif %}
```

**Comment by droans** [comment]
Looks like you need to change `(% set hour...%}` to `{% set hour...%}`

When I made the adjustment, it seemed to work fine for me. I couldn't test the first part beyond printing the result, but I'm guessing they're macros from your personal environment. Calling M112 shuts the printer down as expected. 

If the fix doesn't work or was just a typo, please provide your klippy log. Usually the best way to get the details is to open it just after the error, go all the way to the bottom, and then scroll up a page at a time until you see something other than the stats lines.

**Comment by RoyalStarfox** [comment]
Oddly, it isn't showing me the full code snip you shared. It only shows two short snips that are exactly the same, "{% set hour...%}"

**Comment by RoyalStarfox** [comment]
I have tinkered further with the command, and stripped everything down as far as a simple M118 command, and it still returns with an error. I went ahead and reinstalled the plugin as well, but am still getting the same results, unfortunately.

**Comment by RoyalStarfox** [comment]
Not sure how much of the log you want, but here's what seems to be relevant.
```
Starting heater checks for heater_bed
Starting heater checks for extruder
Stats 50.7: gcodein=5 mcu: mcu_awake=0.000 mcu_task_avg=0.000000 mcu_task_stddev=0.000000 bytes_write=2465 bytes_read=5287 bytes_retransmit=9 bytes_invalid=0 send_seq=219 receive_seq=219 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=4603 freq=119956582 rpi: mcu_awake=0.000 mcu_task_avg=0.000000 mcu_task_stddev=0.000000 bytes_write=778 bytes_read=4131 bytes_retransmit=0 bytes_invalid=0 send_seq=107 receive_seq=107 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=49998745 adj=50006327 heater_bed: target=0 temp=22.8 pwm=0.000 sysload=1.71 cputime=4.006 memavail=7615920 print_time=0.001 buffer_time=0.000 print_stall=0 extruder: target=0 temp=23.8 pwm=0.000
Stats 51.7: gcodein=5 mcu: mcu_awake=0.000 mcu_task_avg=0.000000 mcu_task_stddev=0.000000 bytes_write=7612 bytes_read=5938 bytes_retransmit=9 bytes_invalid=0 send_seq=326 receive_seq=326 retransmit_seq=2 srtt=0.002 rttvar=0.001 rto=0.025 ready_bytes=8 stalled_bytes=0 freq=119953742 rpi: mcu_awake=0.000 mcu_task_avg=0.000000 mcu_task_stddev=0.000000 bytes_write=784 bytes_read=4147 bytes_retransmit=0 bytes_invalid=0 send_seq=108 receive_seq=108 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=49998943 adj=50021488 heater_bed: target=0 temp=22.7 pwm=0.000 sysload=1.71 cputime=4.024 memavail=7616192 print_time=0.001 buffer_time=0.000 print_stall=0 extruder: target=0 temp=25.1 pwm=0.000
Stats 52.7: gcodein=10 mcu: mcu_awake=0.035 mcu_task_avg=0.000032 mcu_task_stddev=0.000071 bytes_write=7631 bytes_read=6066 bytes_retransmit=9 bytes_invalid=0 send_seq=328 receive_seq=328 retransmit_seq=2 srtt=0.001 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=119953723 rpi: mcu_awake=0.005 mcu_task_avg=0.000036 mcu_task_stddev=0.000020 bytes_write=790 bytes_read=4178 bytes_retransmit=0 bytes_invalid=0 send_seq=109 receive_seq=109 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=49999714 adj=50022773 heater_bed: target=0 temp=22.7 pwm=0.000 sysload=1.71 cputime=4.043 memavail=7616192 print_time=0.001 buffer_time=0.000 print_stall=0 extruder: target=0 temp=27.4 pwm=0.000
Stats 53.7: gcodein=10 mcu: mcu_awake=0.035 mcu_task_avg=0.000032 mcu_task_stddev=0.000071 bytes_write=7637 bytes_read=6172 bytes_retransmit=9 bytes_invalid=0 send_seq=329 receive_seq=329 retransmit_seq=2 srtt=0.001 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=119953276 rpi: mcu_awake=0.005 mcu_task_avg=0.000036 mcu_task_stddev=0.000020 bytes_write=796 bytes_read=4194 bytes_retransmit=0 bytes_invalid=0 send_seq=110 receive_seq=110 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=49999794 adj=50023121 heater_bed: target=0 temp=22.8 pwm=0.000 sysload=1.71 cputime=4.054 memavail=7616208 print_time=0.001 buffer_time=0.000 print_stall=0 extruder: target=0 temp=117.0 pwm=0.000
Stats 54.7: gcodein=10 mcu: mcu_awake=0.035 mcu_task_avg=0.000032 mcu_task_stddev=0.000071 bytes_write=7694 bytes_read=6323 bytes_retransmit=9 bytes_invalid=0 send_seq=333 receive_seq=333 retransmit_seq=2 srtt=0.001 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=119953043 rpi: mcu_awake=0.005 mcu_task_avg=0.000036 mcu_task_stddev=0.000020 bytes_write=802 bytes_read=4210 bytes_retransmit=0 bytes_invalid=0 send_seq=111 receive_seq=111 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=49999948 adj=50022684 heater_bed: target=0 temp=22.7 pwm=0.000 sysload=1.71 cputime=4.076 memavail=7616208 print_time=0.001 buffer_time=0.000 print_stall=0 extruder: target=0 temp=127.3 pwm=0.000
Stats 55.7: gcodein=10 mcu: mcu_awake=0.035 mcu_task_avg=0.000032 mcu_task_stddev=0.000071 bytes_write=7751 bytes_read=6444 bytes_retransmit=9 bytes_invalid=0 send_seq=337 receive_seq=337 retransmit_seq=2 srtt=0.001 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=119952925 rpi: mcu_awake=0.005 mcu_task_avg=0.000036 mcu_task_stddev=0.000020 bytes_write=808 bytes_read=4226 bytes_retransmit=0 bytes_invalid=0 send_seq=112 receive_seq=112 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=50000022 adj=50022441 heater_bed: target=0 temp=22.7 pwm=0.000 sysload=1.57 cputime=4.096 memavail=7616208 print_time=0.001 buffer_time=0.000 print_stall=0 extruder: target=0 temp=28.5 pwm=0.000
Stats 56.7: gcodein=10 mcu: mcu_awake=0.035 mcu_task_avg=0.000032 mcu_task_stddev=0.000071 bytes_write=7809 bytes_read=6570 bytes_retransmit=9 bytes_invalid=0 send_seq=342 receive_seq=342 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=119953073 rpi: mcu_awake=0.005 mcu_task_avg=0.000036 mcu_task_stddev=0.000020 bytes_write=814 bytes_read=4242 bytes_retransmit=0 bytes_invalid=0 send_seq=113 receive_seq=113 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=50000029 adj=50022038 heater_bed: target=0 temp=22.6 pwm=0.000 sysload=1.57 cputime=4.115 memavail=7615960 print_time=0.001 buffer_time=0.000 print_stall=0 extruder: target=0 temp=23.8 pwm=0.000
Internal error on command:"FINISHED"
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 182, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/gcode.py", line 120, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 185, in cmd
    kwparams = dict(self.kwparams)
AttributeError: ExtendedGCodeMacro instance has no attribute 'kwparams'
Transition to shutdown state: Internal error on command:"FINISHED"
Dumping gcode input 4 blocks
Read 48.252244: 'M105\n'
Read 52.427609: 'M105\n'
Read 57.428524: 'M105\n'
Read 57.527946: 'FINISHED\n'
gcode state: absolute_coord=True absolute_extrude=True base_position=[0.0, 0.0, 0.0, 0.0] last_position=[0.0, 0.0, 0.0, 0.0] homing_position=[0.0, 0.0, 0.0, 0.0] speed_factor=0.0166666666667 extrude_factor=1.0 speed=25.0
Reactor garbage collection: (48.98357397, 0.0, 0.0)
Internal error on command:"FINISHED"
MCU 'mcu' shutdown: Command request
clocksync state: mcu_freq=120000000 last_clock=1178181097 clock_est=(49.722 333320452 119953038.856) min_half_rtt=0.000077 min_rtt_time=48.530 time_avg=49.722(5.651) clock_avg=333320452.895(677842952.366) pred_variance=8099030834.739
Dumping serial stats: bytes_write=7869 bytes_read=6723 bytes_retransmit=9 bytes_invalid=0 send_seq=348 receive_seq=348 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0
Dumping send queue 100 messages
Sent 0 50.992514 50.992514 49: seq: 18, spi_send oid=6 data='\xfa\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', spi_send oid=6 data='\xf8\x80p\x80\x00'
```

**Comment by droans** [comment]
When did you last update Klipper? Based on the git history, `self.kwparams` was removed from the code in November 2021.

**Comment by RoyalStarfox** [comment]
I was sure I've updated it in the past couple of months, but I could absolutely be wrong. It may have just been a friend's printer I was helping with! I found out why it wasn't updated, though. It was dumb on my part, but the long story short is that it's a massive pain in the rear end to get to the motherboard.

Updated, it's not giving an internal error, anymore! However, it is giving a new error!

```
Send: FINISHED
Recv: !! Error evaluating 'extended_macro FINISHED:gcode': UndefinedError: 'time' is undefined
Recv: ok
```
I've tried referring to it a couple of different ways, but it just keeps acting like I'm not actually declaring the variable, even though I have.

**Comment by droans** [comment]
Can you provide more logs? What you gave before was fantastic. 

I don't see time being used in your previous code nor do we import it.

**Comment by RoyalStarfox** [comment]
I renamed "hour" to "time" while retyping it, so it wasn't a crazy change. 

```
Error evaluating 'extended_macro FINISHED:gcode': UndefinedError: 'time' is undefined
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 61, in render
    return str(self.template.render(context))
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "<template>", line 3, in top-level template code
  File "/home/pi/klippy-env/local/lib/python2.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
UndefinedError: 'time' is undefined
Error evaluating 'extended_macro FINISHED:gcode': UndefinedError: 'time' is undefined

Stats 5601.8: gcodein=5013  mcu: mcu_awake=0.002 mcu_task_avg=0.000008 mcu_task_stddev=0.000012 bytes_write=249276 bytes_read=675945 bytes_retransmit=9 bytes_invalid=0 send_seq=20909 receive_seq=20909 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=12 stalled_bytes=0 freq=119952633 rpi: mcu_awake=0.001 mcu_task_avg=0.000011 mcu_task_stddev=0.000017 bytes_write=31228 bytes_read=97997 bytes_retransmit=0 bytes_invalid=0 send_seq=5179 receive_seq=5179 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=49999130 adj=50018858 heater_bed: target=0 temp=22.6 pwm=0.000 sysload=0.01 cputime=104.853 memavail=7596556 print_time=0.012 buffer_time=0.000 print_stall=0 extruder: target=0 temp=147.1 pwm=0.000
```

**Comment by RoyalStarfox** [comment]
I tracked down what it was, definitely an error on my part as well. Sorry to waste time, and very much thanks for the help!
